### ISSUE TITLE
Opening files sometimes takes multiple clicks

### ISSUE THREAD

**Issue by shubhamgogna** [joshcurtis/Senior-project#12]
Really odd issue, but using the dropdown, it can take multiple clicks to open a file (INI or Text).

**Comment by shubhamgogna** [comment]
I found the cause. The click actions (opening/saving) only occur if you press the element that handles the click. 

``` HTML
<a ...>
  <li ...>Element One</li>
</a>
```

If the `<li>` is the one that handles opening and saving, then clicking the surrounding `<a>` does not perform the action.

**Comment by wmedrano** [comment]
Maybe the inner element can be made bigger?
Pushing the event up seems messy

**Comment by shubhamgogna** [comment]
I'm considering editing the `navbar-dropdown` function to take elements and respective callbacks for `on-click` that I can attach to the `li` tag that will contain the element. Thoughts?
