### ISSUE TITLE
Monitor tab slows down if you leave the window open long enough

### ISSUE THREAD

**Issue by shubhamgogna** [joshcurtis/Senior-project#19]
The simulated measurements keep getting added so the plot renders all of them. Maybe only maintain the last few minutes or maybe keep the all values but only render the first 1 minutes worth?

@wmedrano

**Comment by wmedrano** [comment]
https://github.com/joshcurtis/MachineView/commit/9ff0a15fbd04ddd60ba68592a3af484f100cfff4
