### ISSUE TITLE
Add way to cancel ssh connection attempt

### ISSUE THREAD

**Issue by joshcurtis** [joshcurtis/Senior-project#25]
If I try to connect to, "beaglebone.lcal" I don't want to wait the entire timeout period.

**Comment by shubhamgogna** [comment]
Can we consider lowering the timeout from 15 seconds to 5 seconds? 15 seconds seems excessive. @wmedrano

**Comment by joshcurtis** [comment]
I think I remember 5 being a bit too short for my computer to connect via wifi. 7 or 8 maybe?

**Comment by joshcurtis** [comment]
SSH is ded. #54
