### ISSUE TITLE
Improve debugging output when sftp get tries to get a file that doesn't exist

### ISSUE THREAD

**Issue by joshcurtis** [joshcurtis/Senior-project#33]

**Comment by shubhamgogna** [comment]
@joshcurtis @wmedrano Good to close or did you have something else in mind?

**Comment by joshcurtis** [comment]
Not yet, hopefully I'll finish this during 426 today. 

I think the default error output from shoreleave is to just dump the entire java stacktrace. I'd like to hide that and just print a message like "Failed to retrieve {file}"

**Comment by joshcurtis** [comment]
Done. Going to improve sftp-ls too.

**Comment by joshcurtis** [comment]
We have logging code in the controller and server_interop.core

This should be in one place only. Which do we want?

**Comment by wmedrano** [comment]
I prefer browser, as the existence of the server is an abomination
