### ISSUE TITLE
Plotting Enhancements

### ISSUE THREAD

**Issue by joshcurtis** [joshcurtis/Senior-project#36]
- Show only last X data data points
- automatically store data in case of "emergency"
- Add warning/alert if measurement is outside of range

What else did Ben suggest?

**Comment by wmedrano** [comment]
I'll add these tomorrow

**Comment by wmedrano** [comment]
- ~~Show only last X data data points~~ 6acfd904d2aaeb307facbc4aa241d65dfe41b594
- automatically store data in case of "emergency"
- Add warning/alert if measurement is outside of range

**Comment by joshcurtis** [comment]
@wmedrano done?

**Comment by wmedrano** [comment]
Not the warning
