### ISSUE TITLE
Add a shutdown button

### ISSUE THREAD

**Issue by joshcurtis** [joshcurtis/Senior-project#4]

**Comment by joshcurtis** [comment]
:banana:

**Comment by joshcurtis** [comment]
Working on this in shutdown_mk branch

**Comment by wmedrano** [comment]
:monkey:

**Comment by joshcurtis** [comment]
well the button is there

**Comment by wmedrano** [comment]
Now show only the button that applies

``` Clojure
(if @machinekit-is-running? [...] [...])
```

**Comment by joshcurtis** [comment]
Should finish this tomorrow

**Comment by joshcurtis** [comment]
This is broken

**Comment by wmedrano** [comment]
remote_manger/view.cljs has

``` clojure
(if is-machinekit-running? ...)
```

Which refers to `:is-machinekit-running?` within `app.store/state` ,but it never set/updated

**Comment by joshcurtis** [comment]
Fixed the display issue. Need to hook it up to a socket.

**Comment by joshcurtis** [comment]
Killing the process that runs machinekit afater #54 is merged
