### ISSUE TITLE
Run ZeroMQ client side

### ISSUE THREAD

**Issue by wmedrano** [joshcurtis/Senior-project#46]

**Comment by joshcurtis** [comment]
I'll work on this today and Friday. I expect to have it done by then.

**Comment by wmedrano** [comment]
Did some quick research on this and I'm not sure that ZMQ is ready for the browser

**Comment by joshcurtis** [comment]
What did you find in your research?

**Comment by wmedrano** [comment]
https://github.com/zeromq/JSMQ
- in beta
- the api will probably change

https://github.com/progrium/nullmq
- not well documented
- "this is still ver early."

**Comment by joshcurtis** [comment]
I've tried using JSMQ before. It only uses websockets not TCP sockets so that's out.

I was going to try and run the [node zmq] package (https://www.npmjs.com/package/zmq) in the browser with [browserify](http://browserify.org/)

**Comment by joshcurtis** [comment]
As an alternative, if there are ZMQ bindings on the beaglebone, we could make requests through the server.

**Comment by wmedrano** [comment]
You can't run all node stuff in the browser as some stuff uses C and simply provides a JS interface.
@s-gogna  correct right?

**Comment by joshcurtis** [comment]
It's running server side after #54 is merged.
