### ISSUE TITLE
Add MachineKit State

### ISSUE THREAD

**Issue by joshcurtis** [joshcurtis/Senior-project#5]
Track things like running services.

Possibly add states for each service to keep track of URI?

**Comment by wmedrano** [comment]
Do you have a solution for this?

```
{:services {:service1 {....}
 :mk-launched? false}
```

**Comment by joshcurtis** [comment]
If by "this" you mean discovering services with avahi then no. I'm pretty pessimistic about my ability to quickly make progress on that front. 

The easiest thing to do is to run "python ~/Desktop/run.py" ourselves then parse the output for the services and ports.

**Comment by joshcurtis** [comment]
Going to add state for sockets then mark as completed

**Comment by joshcurtis** [comment]
Added state for sockets in server/state
