### ISSUE TITLE
Cannot switch tabs after pressing the text editor tab

### ISSUE THREAD

**Issue by shubhamgogna** [joshcurtis/Senior-project#6]
@wmedrano The atom/model is returning null which fails the asserts https://github.com/joshcurtis/Senior-project/blob/master/src/cljs/text_editor/view.cljs#L20-L21

**Comment by wmedrano** [comment]
@s-gogna 
https://github.com/joshcurtis/Senior-project/commit/6119162a0666f902861a4073d9628124e2db2827
Fixed by initializing text-editor with empty text mapped to the id [:local "scratch.txt"]

**Comment by wmedrano** [comment]
Leave it open as having a nil selected-id will still error
